### ISSUE TITLE
Got license?

### ISSUE THREAD

**Issue by ghost** [kyshel/jekyll-wordpress-sync#4]
https://choosealicense.com

**Comment by ghost** [comment]
Ah. I see you may have intended `GPLv2` by looking at the **Credits** section of the README. To apply `GPLv2`, or `GPLv2-or-later` you can reference this doc specifically:

https://choosealicense.com/licenses/gpl-2.0/

**Comment by kyshel** [comment]
Thanks!
The LICENSE file has added to the repo. :smiley:

**Comment by ghost** [comment]
Solid, brother. Thank you.
